CREATE DATABASE CINE;
USE CINE;

CREATE TABLE CLIENTE(
CORREO VARCHAR(50) NOT NULL,
NOMBRE CHAR(50) NOT NULL,
CONTRASEÑA VARCHAR(8) NOT NULL,
PRIMARY KEY(CORREO)
);

CREATE TABLE EMPLEADO(
RFC VARCHAR(13) NOT NULL,
NOMBRE CHAR(50) NOT NULL,
APELLIDO CHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
CONTRASEÑA VARCHAR(8) NOT NULL,
PRIMARY KEY(RFC)
);

 CREATE TABLE PELICULA(
TITULO CHAR(30)NOT NULL,
GENERO CHAR(30)NOT NULL,
DURACION INT(3) NOT NULL,
CLASIFICACION CHAR(3) NOT NULL,
SINOPSIS TEXT NOT NULL,
PRIMARY KEY(TITULO),
CONSTRAINT CHK_CLASIF_PELICULA CHECK(CLASIFICACION IN('A','B','B15','C','D'))
);

CREATE TABLE SALA(
NUMERO_SALA INT(3)NOT NULL,
CAPACIDAD INT(3)NOT NULL,
PRIMARY KEY(NUMERO_SALA)
);

CREATE TABLE FUNCION(
ID_FUNCION INT(10) NOT NULL,
TITULO_P CHAR(30) NOT NULL,
NUM_SALA INT(3) NOT NULL,
FECHA_FUNCION DATE NOT NULL,
HORA_FUNCION TIME NOT NULL,
PRECIO DECIMAL NOT NULL,
PRIMARY KEY(ID_FUNCION,TITULO_P,NUM_SALA),
CONSTRAINT FK_TITULOPELI_FUNCION FOREIGN KEY (TITULO_P) REFERENCES PELICULA(TITULO),
CONSTRAINT FK_NUMSALA_FUNCION FOREIGN KEY (NUM_SALA) REFERENCES SALA(NUMERO_SALA)
);

CREATE TABLE FORMA_PAGO(
ID_PAGO INT(10) NOT NULL,
TIPO_PAGO CHAR(20) NOT NULL,
DESCRIPCION CHAR(20) NOT NULL,
PRIMARY KEY(ID_PAGO)
);

CREATE TABLE BOLETO(
FOLIO INT(5) NOT NULL,
CORREO_CLIENTE VARCHAR(50) NOT NULL,
RFC_E VARCHAR(13) NOT NULL,
ID_FUNCION_B INT(10) NOT NULL,
ID_PAGO_B INT(10) NOT NULL,
ASIENTO VARCHAR(3) NOT NULL,
PRECIO_FINAL DECIMAL NOT NULL,
FECHA_HORA_COMPRA DATETIME NOT NULL,
ESTADO_BOLETO SMALLINT(2) NOT NULL,
CODIGO_QR VARCHAR(50) UNIQUE,
PRIMARY KEY (FOLIO),
CONSTRAINT FK_CORREO_BOLETO FOREIGN KEY (CORREO_CLIENTE) REFERENCES CLIENTE(CORREO),
CONSTRAINT FK_RFC_BOLETO FOREIGN KEY (RFC_E) REFERENCES EMPLEADO(RFC),
CONSTRAINT FK_FUNCION_BOLETO FOREIGN KEY (ID_FUNCION_B) REFERENCES FUNCION(ID_FUNCION),
CONSTRAINT FK_PAGO_BOLETO FOREIGN KEY (ID_PAGO_B) REFERENCES FORMA_PAGO(ID_PAGO),
CONSTRAINT CHK_ESTADO_B CHECK(ESTADO_BOLETO IN(1,0)) # 0 ="VENDIDO" 1="CANCELADO"
);
